# Generated by Django 5.0.6 on 2024-06-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amwell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_patient',
            field=models.TextField(max_length=230),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_provider',
            field=models.TextField(max_length=200),
        ),
    ]
