# Generated by Django 5.0.6 on 2024-06-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amwell', '0002_alter_customuser_is_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_patient',
            field=models.TextField(max_length=130),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_provider',
            field=models.TextField(max_length=100),
        ),
    ]
